### ISSUE TITLE
choosing spatial resolution

### ISSUE THREAD

**Issue by agohin** [magpiemodel/magpie#356]
Dear all, 
hope that the pandemics do not hurt you. 
And that you have been able to progress on your researches. 
In particular, on data, something new ? 
Best

**Comment by tscheypidi** [comment]
Hi @agohin,

unfortunately, it is (as often) more complicated to adjust our preprocessing so that the spatial resolution can be chosen afterwards, but we are currently actively working on it. Current estimate would is to have something available by end of January, but as with my previous estimate there might be additional hurdles on the way which might delay it even further.

Best, Jan
